"""
language パラメータ効果検証スクリプト（Base モデル）

- 目的: generate_voice_clone() の language パラメータが日本語漢字の発音に与える影響を検証する。
        language="Auto"（デフォルト）と language="ja" を同一テキストで比較し、
        中国語読みの混入（Issue #26）が language="ja" で改善するかを確認する。
- 対象: Issue #31 の調査担当者
- 関連: Issue #26 — 日本語漢字の中国語読み混入（既知の制約）
         Issue #31 — language パラメータによる日本語発音改善の検証

作成者: 宗廣 颯山
作成日: 2026-04-14
最終更新者: 宗廣 颯山
最終更新日: 2026-04-14

Usage:
    # Base モデルで language パラメータ比較（参照音声が必要）
    docker compose run qwen-tts python3 scripts/test_language_param.py \\
        --ref-audio sample_audio/reference.wav \\
        --ref-text "参照音声のテキスト"

    # speaker profile を使って実行
    docker compose run qwen-tts python3 scripts/test_language_param.py \\
        --profile speaker_profiles/default.pt

    # x-vector モードで実行（ref-text 不要）
    docker compose run qwen-tts python3 scripts/test_language_param.py \\
        --ref-audio sample_audio/reference.wav \\
        --x-vector-only
"""

import argparse
import datetime
import logging
import pathlib
import sys
import time

import numpy as np
import soundfile as sf

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

try:
    import torch
except ImportError:
    logger.error("torch not found. Are you running inside the Docker container?")
    sys.exit(1)

try:
    from qwen_tts import Qwen3TTSModel
except ImportError:
    logger.error("qwen_tts not found. Run: pip install qwen-tts")
    sys.exit(1)

from model_utils import ensure_model_downloaded, load_speaker_profile  # noqa: E402

BASE_MODEL_ID = "Qwen/Qwen3-TTS-12Hz-1.7B-Base"

# ─── テストケース定義 ─────────────────────────────────────────────────────────
# 各ケースを language="Auto" と language="ja" の両方で実行し、ペアで比較する。

TEST_TEXTS = [
    {
        "id": "TC-LANG-01",
        "text": "音声合成の技術は急速に発展しています。自然な日本語の発音と抑揚が再現できるか確認します。",
        "description": "日本語漢字（Issue #26 の問題文）",
    },
    {
        "id": "TC-LANG-02",
        "text": "人工知能は現代社会において重要な役割を果たしています。特に音声認識と音声合成の分野では目覚ましい進歩があります。",  # noqa: E501
        "description": "日本語漢字（長文）",
    },
    {
        "id": "TC-LANG-03",
        "text": "今日はQwen TTSのテストをしています。This is a mixed language test combining Japanese and English.",
        "description": "日英混在テキスト",
    },
    {
        "id": "TC-LANG-04",
        "text": "こんにちは、これはQwen音声合成システムのテストです。よろしくお願いします。",
        "description": "日本語ひらがな/カタカナ混じり",
    },
]

LANGUAGES_TO_TEST = [None, "ja"]  # None → "Auto" (デフォルト)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare language=Auto vs language=ja for Japanese TTS with Base model.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--profile",
        type=pathlib.Path,
        metavar="PATH",
        help="Speaker profile .pt file (pre-generated by create_speaker_profile.py).",
    )
    group.add_argument(
        "--ref-audio",
        type=pathlib.Path,
        metavar="WAV",
        help="Reference audio WAV file (24kHz mono).",
    )
    parser.add_argument(
        "--ref-text",
        type=str,
        default=None,
        metavar="TEXT",
        help="Transcript of the reference audio (enables ICL mode). Requires --ref-audio.",
    )
    parser.add_argument(
        "--x-vector-only",
        action="store_true",
        help="Use x-vector only mode (no ICL). Requires --ref-audio.",
    )
    return parser.parse_args()


def run_test(
    model: Qwen3TTSModel,
    text: str,
    language: str | None,
    tc_id: str,
    output_path: pathlib.Path,
    *,
    speaker_profile=None,
    ref_audio: pathlib.Path | None = None,
    ref_text: str | None = None,
    x_vector_only: bool = False,
) -> dict:
    """1 テキスト × 1 language で音声合成を実行し結果を返す。

    Args:
        model: ロード済み Qwen3TTSModel。
        text: 合成テキスト。
        language: TTS の言語指定。None → "Auto"。
        tc_id: テストケース ID（ログ表示用）。
        output_path: WAV 保存先パス。
        speaker_profile: ロード済み VoiceClonePromptItem（--profile 時）。
        ref_audio: 参照音声パス（--ref-audio 時）。
        ref_text: 参照音声テキスト（ICL モード用）。
        x_vector_only: True → x-vector のみモード。

    Returns:
        結果辞書 (passed, duration_sec, latency_sec, max_amplitude, error)。
    """
    lang_label = language if language is not None else "Auto"
    logger.info("  [%s lang=%s] %s...", tc_id, lang_label, text[:50])

    result = {
        "language": lang_label,
        "passed": False,
        "duration_sec": None,
        "latency_sec": None,
        "max_amplitude": None,
        "error": None,
    }

    try:
        t0 = time.perf_counter()

        if speaker_profile is not None:
            wavs, sample_rate = model.generate_voice_clone(
                text=text,
                language=language,
                voice_clone_prompt=[speaker_profile],
            )
        elif ref_text is not None:
            wavs, sample_rate = model.generate_voice_clone(
                text=text,
                language=language,
                ref_audio=str(ref_audio),
                ref_text=ref_text,
                x_vector_only_mode=False,
            )
        else:
            # x-vector のみモード
            wavs, sample_rate = model.generate_voice_clone(
                text=text,
                language=language,
                ref_audio=str(ref_audio),
                x_vector_only_mode=True,
            )

        latency = time.perf_counter() - t0
        wav = wavs[0]
        duration = len(wav) / sample_rate
        max_amp = float(np.max(np.abs(wav)))

        sf.write(str(output_path), wav, sample_rate)

        result["latency_sec"] = round(latency, 2)
        result["duration_sec"] = round(duration, 2)
        result["max_amplitude"] = round(max_amp, 4)
        result["passed"] = max_amp > 0.01 and duration >= 0.5

        logger.info(
            "    → duration=%.2fs, latency=%.2fs, max_amp=%.4f [%s]",
            duration,
            latency,
            max_amp,
            "PASS" if result["passed"] else "FAIL",
        )

    except Exception as exc:
        result["error"] = str(exc)
        logger.error("    → FAIL: %s", exc)

    return result


def print_summary(all_results: list[dict]) -> None:
    """結果を Auto vs ja の比較形式で表示する。

    Args:
        all_results: run_test が返す辞書に tc_id, description を付加したリストのリスト。
    """
    print("\n" + "=" * 80)
    print("language パラメータ比較 — Auto vs ja")
    print("=" * 80)
    print(f"{'TC':<14} {'説明':<28} {'lang':<6} {'結果':<6} {'秒数':>7} {'遅延':>7} {'最大振幅':>10}")
    print("-" * 80)

    for entry in all_results:
        tc_id = entry["id"]
        desc = entry["description"][:26]
        for r in entry["results"]:
            status = "PASS" if r["passed"] else "FAIL"
            dur = f"{r['duration_sec']:.2f}s" if r["duration_sec"] is not None else "—"
            lat = f"{r['latency_sec']:.2f}s" if r["latency_sec"] is not None else "—"
            amp = f"{r['max_amplitude']:.4f}" if r["max_amplitude"] is not None else "—"
            print(f"{tc_id:<14} {desc:<28} {r['language']:<6} {status:<6} {dur:>7} {lat:>7} {amp:>10}")
            if r["error"]:
                print(f"  └ ERROR: {r['error']}")
        print()

    total_cases = sum(len(e["results"]) for e in all_results)
    passed_cases = sum(r["passed"] for e in all_results for r in e["results"])
    print("-" * 80)
    print(f"総合: {passed_cases}/{total_cases} PASS")
    print("=" * 80)
    print(
        "\n注意: 自動合否は max_amplitude > 0.01 のみ確認します。"
        "\n      中国語読みの改善は生成された WAV ファイルを再生して主観評価してください。"
        "\n      output/ ディレクトリ内の *_auto.wav vs *_ja.wav を聴き比べてください。"
    )


def main() -> None:
    args = parse_args()

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = pathlib.Path("/workspace/output") / f"language_test_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=True)
    logger.info("Output directory: %s", output_dir)

    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    logger.info("Device: %s", device)

    logger.info("Loading model: %s", BASE_MODEL_ID)
    model_path = ensure_model_downloaded(BASE_MODEL_ID)
    model = Qwen3TTSModel.from_pretrained(
        model_path,
        device_map=device,
        dtype=torch.float16,
        low_cpu_mem_usage=True,
        max_memory={0: "60GiB"},
    )
    logger.info("Model loaded.")

    # 話者プロファイルのセットアップ
    speaker_profile = None
    ref_audio = None
    ref_text = None
    x_vector_only = False

    if args.profile:
        logger.info("Loading speaker profile: %s", args.profile)
        speaker_profile = load_speaker_profile(args.profile, device=device)
    else:
        if not args.ref_audio.exists():
            logger.error("Reference audio not found: %s", args.ref_audio)
            sys.exit(1)
        ref_audio = args.ref_audio
        ref_text = args.ref_text
        x_vector_only = args.x_vector_only
        mode = "ICL" if ref_text else "x-vector only"
        logger.info("Reference audio: %s (mode=%s)", ref_audio, mode)

    all_results: list[dict] = []

    for tc in TEST_TEXTS:
        logger.info("\n--- %s: %s ---", tc["id"], tc["description"])
        tc_results = []

        for lang in LANGUAGES_TO_TEST:
            lang_label = lang if lang is not None else "auto"
            output_path = output_dir / f"{tc['id'].lower()}_{lang_label}.wav"

            result = run_test(
                model=model,
                text=tc["text"],
                language=lang,
                tc_id=tc["id"],
                output_path=output_path,
                speaker_profile=speaker_profile,
                ref_audio=ref_audio,
                ref_text=ref_text,
                x_vector_only=x_vector_only,
            )
            tc_results.append(result)

        all_results.append(
            {
                "id": tc["id"],
                "description": tc["description"],
                "results": tc_results,
            }
        )

    print_summary(all_results)

    all_passed = all(r["passed"] for e in all_results for r in e["results"])
    if not all_passed:
        sys.exit(1)


if __name__ == "__main__":
    main()
